### PR TITLE
Automatically gets latest version

### PR DESCRIPTION
**Pull request by plato79**
I made some changes to your docker build. To truly get the latest version I had to add "git" into the image so I changed it. It downgraded python to 3.8 but it doesn't need 3.9 features anyway.

It now pulls the latest GoldHEN repo, get the last file alphabetically ( I suppose it'll always be the last one ) then get rid of others.

Feel free to check..

### CODE REVIEW

**Comment by mc-17** [comment]
Hey! 

Good feature - I'd been working on something similar on my local copy, so I'll merge that, but if you can make a PR for the docker compose stuff I'll merge it :)

**Comment by plato79** [comment]
Do you want me to remove docker-compose file? I use it to automate in my docker setup with `docker-compose build` and `docker-compose up -d` commands.

**Comment by plato79** [comment]
BTW, I saw your code with updating GoldHen.. It's elegant and it doesn't need a docker update, or git module in the docker image. Maybe it's better that you keep your code like this.

**Comment by mc-17** [comment]
> BTW, I saw your code with updating GoldHen.. It's elegant and it doesn't need a docker update, or git module in the docker image. Maybe it's better that you keep your code like this.

Thank you! I really like your docker file changes.

What I mean is can you make a PR with just the docker stuff? I will merge that :) I don't know docker as well as you, so appreciate your help

Thank you for your contributions

**Comment by mc-17** [comment]
Hey @plato79 , any update?

**Comment by plato79** [comment]
> > BTW, I saw your code with updating GoldHen.. It's elegant and it doesn't need a docker update, or git module in the docker image. Maybe it's better that you keep your code like this.
> 
> Thank you! I really like your docker file changes.
> 
> What I mean is can you make a PR with just the docker stuff? I will merge that :) I don't know docker as well as you, so appreciate your help
> 
> Thank you for your contributions

Ah, now I understand... My docker file is pretty simple and not very different from yours. The different parts are there because it pulls GoldHen with git, and executes a python file to get latest version. So, that's why I said your version is enough on its' own. You could ignore this pull request. Although, I'll probably pull your changes on modifiable port / interface on your code.

**Pull request closed without merging**
